<?php
/**
 * @author Jan Habbo Brüning <jan.habbo.bruening@gmail.com>
 *
 * @noinspection PhpUnnecessaryLocalVariableInspection
 * @noinspection SqlNoDataSourceInspection
 * @noinspection PhpFullyQualifiedNameUsageInspection
 */

namespace Frootbox\Ext\Core\Navigation\Navigations\Items;

class Dummy extends AbstractItem
{
    protected $isAutogenerated = true;

    /**
     * @return string
     */
    public function getHref(): string
    {
        if (empty($this->data['href'])) {
            return '#';
        }

        return $this->data['href'];
    }

    /**
     * @return string
     */
    public function getPath(): string
    {

    }

    /**
     * @return string|null
     */
    public function getSubtitle(): ?string
    {
        return $this->data['subtitle'] ?? null;
    }

    /**
     *
     */
    public function updateFromPost(\Frootbox\Http\Post $post): void
    {

    }

    /**
     * @param array|null $prameters
     * @return bool
     */
    public function isActive(array $prameters = null): bool
    {
        $href = $this->getHref();

        if (SERVER_PATH != '/') {
            $href = str_replace(SERVER_PATH, '', $href);
        }

        $href = trim($href, '/');

        return REQUEST == $href;
    }
}
