<?php
/**
 *
 */

namespace Frootbox\Ext\Core\Navigation\Navigations\Items;

class Dummy extends AbstractItem
{
    protected $isAutogenerated = true;

    /**
     *
     */
    public function getHref(): string
    {
        if (empty($this->data['href'])) {
            return '#';
        }

        return $this->data['href'];
    }

    /**
     *
     */
    public function getPath(): string
    {

    }

    /**
     *
     */
    public function updateFromPost(\Frootbox\Http\Post $post): void
    {

    }

    /**
     *
     */
    public function isActive(array $prameters = null): bool
    {
        $href = $this->getHref();

        if (SERVER_PATH != '/') {
            $href = str_replace(SERVER_PATH, '', $href);
        }

        $href = trim($href, '/');

        return REQUEST == $href;
    }
}
