<?php return array (
  0 => 
  array (
    'table' => 
    array (
      'Name' => 'admin_apps',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'icon',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(24)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'menuId',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => 'Global',
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  1 => 
  array (
    'table' => 
    array (
      'Name' => 'aliases',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'itemId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'itemModel',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'status',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => '200',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'payload',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'type',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => 'Generic',
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  2 => 
  array (
    'table' => 
    array (
      'Name' => 'assets',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'parentId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'customClass',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'dateStart',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'dateEnd',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      13 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '14',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      14 => 
      array (
        'COLUMN_NAME' => 'state',
        'ORDINAL_POSITION' => '15',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      15 => 
      array (
        'COLUMN_NAME' => 'visibility',
        'ORDINAL_POSITION' => '16',
        'COLUMN_DEFAULT' => '1',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  3 => 
  array (
    'table' => 
    array (
      'Name' => 'blocks',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'uid',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'blockId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  4 => 
  array (
    'table' => 
    array (
      'Name' => 'categories',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'rootId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'parentId',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'lft',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'rgt',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'model',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      13 => 
      array (
        'COLUMN_NAME' => 'uid',
        'ORDINAL_POSITION' => '14',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      14 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '15',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      15 => 
      array (
        'COLUMN_NAME' => 'visibility',
        'ORDINAL_POSITION' => '16',
        'COLUMN_DEFAULT' => '1',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  5 => 
  array (
    'table' => 
    array (
      'Name' => 'categories_2_items',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'categoryId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'categoryClass',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'itemId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'itemClass',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  6 => 
  array (
    'table' => 
    array (
      'Name' => 'content_elements',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'parentId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'socket',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'type',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'inheritance',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => 'None',
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'visibility',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => 'Public',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(16)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  7 => 
  array (
    'table' => 
    array (
      'Name' => 'content_texts',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'userId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'uid',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'text',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  8 => 
  array (
    'table' => 
    array (
      'Name' => 'content_widgets',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'userId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'textUid',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  9 => 
  array (
    'table' => 
    array (
      'Name' => 'extensions',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'vendorId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'extensionId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'isactive',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'version',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  10 => 
  array (
    'table' => 
    array (
      'Name' => 'files',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'userId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'folderId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'masterId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'name',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'description',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'type',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'size',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'path',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      13 => 
      array (
        'COLUMN_NAME' => 'uid',
        'ORDINAL_POSITION' => '14',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      14 => 
      array (
        'COLUMN_NAME' => 'copyright',
        'ORDINAL_POSITION' => '15',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      15 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '16',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  11 => 
  array (
    'table' => 
    array (
      'Name' => 'locations',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'street',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'streetNumber',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'zipcode',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'city',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      13 => 
      array (
        'COLUMN_NAME' => 'country',
        'ORDINAL_POSITION' => '14',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      14 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '15',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      15 => 
      array (
        'COLUMN_NAME' => 'phone',
        'ORDINAL_POSITION' => '16',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      16 => 
      array (
        'COLUMN_NAME' => 'email',
        'ORDINAL_POSITION' => '17',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      17 => 
      array (
        'COLUMN_NAME' => 'fax',
        'ORDINAL_POSITION' => '18',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      18 => 
      array (
        'COLUMN_NAME' => 'url',
        'ORDINAL_POSITION' => '19',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  12 => 
  array (
    'table' => 
    array (
      'Name' => 'logs',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'logdata',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  13 => 
  array (
    'table' => 
    array (
      'Name' => 'pages',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'rootId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'parentId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'lft',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'rgt',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'language',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => 'de-DE',
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(8)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'visibility',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => 'Public',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(16)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  14 => 
  array (
    'table' => 
    array (
      'Name' => 'persons',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'orderId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'className',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'gender',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'firstName',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'lastName',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'phone',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'email',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      13 => 
      array (
        'COLUMN_NAME' => 'position',
        'ORDINAL_POSITION' => '14',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      14 => 
      array (
        'COLUMN_NAME' => 'company',
        'ORDINAL_POSITION' => '15',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      15 => 
      array (
        'COLUMN_NAME' => 'street',
        'ORDINAL_POSITION' => '16',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      16 => 
      array (
        'COLUMN_NAME' => 'streetNumber',
        'ORDINAL_POSITION' => '17',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      17 => 
      array (
        'COLUMN_NAME' => 'city',
        'ORDINAL_POSITION' => '18',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      18 => 
      array (
        'COLUMN_NAME' => 'zipcode',
        'ORDINAL_POSITION' => '19',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  15 => 
  array (
    'table' => 
    array (
      'Name' => 'shop_products',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'datasheetId',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'title',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'alias',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'price',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'float',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'float',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'taxrate',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'float',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'float',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      10 => 
      array (
        'COLUMN_NAME' => 'isFree',
        'ORDINAL_POSITION' => '11',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      11 => 
      array (
        'COLUMN_NAME' => 'itemNumber',
        'ORDINAL_POSITION' => '12',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      12 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '13',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      13 => 
      array (
        'COLUMN_NAME' => 'shippingId',
        'ORDINAL_POSITION' => '14',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      14 => 
      array (
        'COLUMN_NAME' => 'packagingSize',
        'ORDINAL_POSITION' => '15',
        'COLUMN_DEFAULT' => '1',
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      15 => 
      array (
        'COLUMN_NAME' => 'packagingUnit',
        'ORDINAL_POSITION' => '16',
        'COLUMN_DEFAULT' => 'Each',
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      16 => 
      array (
        'COLUMN_NAME' => 'visibility',
        'ORDINAL_POSITION' => '17',
        'COLUMN_DEFAULT' => '2',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  16 => 
  array (
    'table' => 
    array (
      'Name' => 'shop_products_data',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'productId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'fieldId',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'valueText',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  17 => 
  array (
    'table' => 
    array (
      'Name' => 'tags',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'itemId',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'itemClass',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'config',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'text',
        'CHARACTER_SET_NAME' => 'utf8',
        'COLLATION_NAME' => 'utf8_general_ci',
        'COLUMN_TYPE' => 'text',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'pageId',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      7 => 
      array (
        'COLUMN_NAME' => 'pluginId',
        'ORDINAL_POSITION' => '8',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      8 => 
      array (
        'COLUMN_NAME' => 'tag',
        'ORDINAL_POSITION' => '9',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      9 => 
      array (
        'COLUMN_NAME' => 'category',
        'ORDINAL_POSITION' => '10',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
  18 => 
  array (
    'table' => 
    array (
      'Name' => 'users',
      'Engine' => 'InnoDB',
      'Collation' => 'utf8mb4_general_ci',
    ),
    'columns' => 
    array (
      0 => 
      array (
        'COLUMN_NAME' => 'id',
        'ORDINAL_POSITION' => '1',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'int',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'int(11)',
        'COLUMN_KEY' => 'PRI',
        'EXTRA' => 'auto_increment',
      ),
      1 => 
      array (
        'COLUMN_NAME' => 'date',
        'ORDINAL_POSITION' => '2',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      2 => 
      array (
        'COLUMN_NAME' => 'updated',
        'ORDINAL_POSITION' => '3',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      3 => 
      array (
        'COLUMN_NAME' => 'email',
        'ORDINAL_POSITION' => '4',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      4 => 
      array (
        'COLUMN_NAME' => 'password',
        'ORDINAL_POSITION' => '5',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'latin1',
        'COLLATION_NAME' => 'latin1_swedish_ci',
        'COLUMN_TYPE' => 'varchar(255)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      5 => 
      array (
        'COLUMN_NAME' => 'lastClick',
        'ORDINAL_POSITION' => '6',
        'COLUMN_DEFAULT' => NULL,
        'IS_NULLABLE' => 'YES',
        'DATA_TYPE' => 'datetime',
        'CHARACTER_SET_NAME' => NULL,
        'COLLATION_NAME' => NULL,
        'COLUMN_TYPE' => 'datetime',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
      6 => 
      array (
        'COLUMN_NAME' => 'type',
        'ORDINAL_POSITION' => '7',
        'COLUMN_DEFAULT' => 'Admin',
        'IS_NULLABLE' => 'NO',
        'DATA_TYPE' => 'varchar',
        'CHARACTER_SET_NAME' => 'utf8mb4',
        'COLLATION_NAME' => 'utf8mb4_general_ci',
        'COLUMN_TYPE' => 'varchar(45)',
        'COLUMN_KEY' => '',
        'EXTRA' => '',
      ),
    ),
  ),
);